# display.yaml

substitutions:
  startup_sound_file: "/config/esphome/media/Home_Connected.flac"
  ha_weather_entity: weather.forecast_maison

font:

  - file:
      type: gfonts
      family: Figtree
      weight: 300
    id: font_display
    size: 18
    glyphsets:
      - GF_Latin_Core

  - file:
      type: gfonts
      family: Figtree
      weight: 600
    id: font_boot
    size: 34
    glyphsets:
      - GF_Latin_Core

  - file: "/config/esphome/fonts/DSEG7ClassicMini-Bold.ttf"
    id: font_7seg
    size: 42
    glyphs: "0123456789:- "

  - file:
      type: gfonts
      family: Figtree
      weight: 700
    id: font_temp_big
    size: 58
    glyphs: "0123456789-"

  - file:
      type: gfonts
      family: Figtree
      weight: 700
    id: font_temp_unit
    size: 22

  - file: "/config/esphome/fonts/materialdesignicons-webfont.ttf"
    id: font_mdi_tech
    size: 24
    bpp: 4
    glyphs:
      - "\U000F036c" # Micro on
      - "\U000F036d" # Micro off
      - "\U000F007A" # mdi-battery-10
      - "\U000F007B" # mdi-battery-20
      - "\U000F007C" # mdi-battery-30
      - "\U000F007D" # mdi-battery-40
      - "\U000F007E" # mdi-battery-50
      - "\U000F007F" # mdi-battery-60
      - "\U000F0080" # mdi-battery-70
      - "\U000F0081" # mdi-battery-80
      - "\U000F0082" # mdi-battery-90
      - "\U000F0079" # mdi-battery (full)
      - "\U000F008E" # mdi-battery-outline
      - "\U000F0091" # mdi-battery-unknown
      - "\U000F06a5" # Power plug on
      - "\U000F06a6" # Powwer plug off
      - "\U000F1425" # Powwer plug outline
      - "\U000F0370" # Micro plug in
      - "\U000F0371" # Micro plug out
      - "\U000F05A9" # Wifi

  - file: "/config/esphome/fonts/materialdesignicons-webfont.ttf"
    id: font_mdi_weather
    size: 48
    bpp: 4
    glyphs:
      - "\U000F0590"
      - "\U000F0592"
      - "\U000F0593"
      - "\U000F0595"
      - "\U000F0596"
      - "\U000F0597"
      - "\U000F0598"
      - "\U000F0599"

api:
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: lbl_hastatus
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: lbl_hastatus

text_sensor:

  - platform: template
    id: clock_hm
    update_interval: 1s
    lambda: |-
      auto t = id(homeassistant_time).now();
      if (!t.is_valid()) return std::string("--:--:--");
      bool hide_colons = ((t.second % 2) == 0);
      char buf[9];
      if (hide_colons) snprintf(buf, sizeof(buf), "%02d %02d %02d", t.hour, t.minute, t.second);
      else snprintf(buf, sizeof(buf), "%02d:%02d:%02d", t.hour, t.minute, t.second);
      return std::string(buf);
    on_value:
      - if:
          condition:
            lvgl.page.is_showing: waitingBP
          then:
            - lvgl.label.update:
                id: clock_label_waitingBP
                text: !lambda return x;
      - if:
          condition:
            lvgl.page.is_showing: answeringP
          then:
            - lvgl.label.update:
                id: clock_label_answeringP
                text: !lambda return x;

  - platform: template
    id: chanel_ha
    update_interval: 1s
    lambda: |-
      return id(homeassistant_chanel).state;
    on_value:
      - if:
          condition:
            lvgl.page.is_showing: waitingBP
          then:
            - lvgl.label.update:
                id: chanel_waitingBP
                text: !lambda return x;

  - platform: template
    id: chanel_menu
    update_interval: 1s
    lambda: |-
      return id(menu_chanel).state;
    on_value:
      - if:
          condition:
            lvgl.page.is_showing: waitingBP
          then:
            - lvgl.label.update:
                id: menu_waitingBP
                text: !lambda return x;

  - platform: template
    id: disp_status
    update_interval: 1s
    lambda: |-
      return id(txt_status).state;
    on_value:
      - if:
          condition:
            lvgl.page.is_showing: waitingBP
          then:
            - lvgl.label.update:
                id: disp_status_waitingBP
                text: !lambda return x;

  - platform: template
    id: vol_int
    update_interval: 1s
    lambda: |-
      int display_volume = (int) (id(Vol) * 100.0f);
      char buffer[10]; 
      sprintf(buffer, "%d", display_volume);
      //auto n = parse_number<int>(buffer);
      return std::string(buffer);
    on_value:
      #- logger.log:
      #      format: "vol: %d == %f"
      #      args: [ stoi(x), 'id(Vol)' ]
      - if:
          condition:
            lvgl.page.is_showing: waitingBP
          then:
            - lvgl.bar.update:
                id: bar_vol_id
                #value: !lambda return x;
                value: !lambda return stoi(x);
                #value: 30

  - platform: template
    id: disp_mute
    update_interval: 1s
    lambda: |-
      char buffer[10]; 
      sprintf(buffer, "%d", id(mute));
      return std::string(buffer);
    on_value:
      - if:
          condition:
            lambda: return (stoi(x) == 1);
          then:
            - lvgl.bar.update:
                id: bar_vol_id
                indicator:
                  bg_color: 0xFF0000
          else:
            - lvgl.bar.update:
                id: bar_vol_id
                indicator:
                  bg_color: 0x0000FF

  - platform: template
    id: disp_mic_mute
    update_interval: 1s
    lambda: |-
      char buffer[10]; 
      sprintf(buffer, "%d", id(mic_muted));
      return std::string(buffer);
    on_value:
      - if:
          condition:
            lambda: return (stoi(x) == 1);
          then:
            - lvgl.label.update:
                id: disp_micro_waitingBP
                text: "\U000F036d"
                text_color: 0x00FF00
          else:
            - lvgl.label.update:
                id: disp_micro_waitingBP
                text: "\U000F036c"
                text_color: 0xFF0000

  - platform: template
    id: disp_microplug
    update_interval: 1s
    lambda: |-
      char buffer[10]; 
      sprintf(buffer, "%d", id(jack_detect).state);
      return std::string(buffer);
    on_value:
      - if:
          condition:
            lambda: return (stoi(x) == 1);
          then:
            - lvgl.label.update:
                id: disp_microplug_waitingBP
                text: "\U000F0370"
                text_color: 0x00FF00
          else:
            - lvgl.label.update:
                id: disp_microplug_waitingBP
                text: "\U000F0371"
                text_color: 0xFF0000

  - platform: template
    id: disp_powerplug
    update_interval: 1s
    lambda: |-
      char buffer[10]; 
      sprintf(buffer, "%d", id(usb_power_detect).state);
      return std::string(buffer);
    on_value:
      - if:
          condition:
            lambda: return (stoi(x) == 1);
          then:
            - lvgl.label.update:
                id: disp_powerplug_waitingBP
                text: "\U000F06a5"
                text_color: 0x00FF00
          else:
            - lvgl.label.update:
                id: disp_powerplug_waitingBP
                text: "\U000F06a6"
                text_color: 0xFF0000

  - platform: homeassistant
    id: ha_weather_condition
    entity_id: ${ha_weather_entity}
    on_value:
      - lambda: |-
          const char* icon = "\U000F0590";
          auto c = id(ha_weather_condition).state;

          if (c == "sunny" || c == "clear") {
            icon = "\U000F0599";
          } else if (c == "partlycloudy") {
            icon = "\U000F0595";
          } else if (c == "cloudy") {
            icon = "\U000F0590";
          } else if (c == "rainy") {
            icon = "\U000F0597";
          } else if (c == "pouring") {
            icon = "\U000F0596";
          } else if (c == "snowy") {
            icon = "\U000F0598";
          } else if (c == "lightning") {
            icon = "\U000F0593";
          } else if (c == "hail") {
            icon = "\U000F0592";
          }

          lv_label_set_text(id(weather_icon_glow), icon);
          lv_label_set_text(id(weather_icon), icon);

  - platform: template
    id: weather_temp_big
    update_interval: 15s
    lambda: |-
      if (!id(ha_weather_temperature).has_state()) return std::string("--");
      int ti = (int) lroundf(id(ha_weather_temperature).state);
      char buf[8];
      snprintf(buf, sizeof(buf), "%d", ti);
      return std::string(buf);
    on_value:
      - if:
          condition:
            lvgl.page.is_showing: waitingBP
          then:
            - lvgl.label.update:
                id: weather_big_temp
                text: !lambda return x;

sensor:

  - platform: homeassistant
    id: ha_weather_temperature
    entity_id: ${ha_weather_entity}
    attribute: temperature

  - platform: template
    id: sns_battery_percentage
    update_interval: 1s
    lambda: |-
      return id(battery_percent).state;
    on_value:
      - lvgl.label.update:
          id: lbl_battery_status
          text: !lambda |-
            static char buf[10];
            std::string icon;
            if (x == 100) {
                icon = "\U000F0079"; // mdi-battery (full)
            } else if (x > 90) {
                icon = "\U000F0082"; // mdi-battery-90
            } else if (x > 80) {
                icon = "\U000F0081"; // mdi-battery-80
            } else if (x > 70) {
                icon = "\U000F0080"; // mdi-battery-70
            } else if (x > 60) {
                icon = "\U000F007F"; // mdi-battery-60
            } else if (x > 50) {
                icon = "\U000F007E"; // mdi-battery-50
            } else if (x > 40) {
                icon = "\U000F007D"; // mdi-battery-40
            } else if (x > 30) {
                icon = "\U000F007C"; // mdi-battery-30
            } else if (x > 20) {
                icon = "\U000F007B"; // mdi-battery-20
            } else if (x > 10) {
                icon = "\U000F007A"; // mdi-battery-10
            } else if (x > 0) {
                icon = "\U000F008E"; // mdi-battery-outline
            } else {
                icon = "\U000F0091"; // mdi-battery-unknown
            }
            snprintf(buf, sizeof(buf), "%s", icon.c_str());
            return buf;
          text_color: !lambda |-
            int color = 0x808080;
            if (x > 70) {
               color = 0xFFFF00;
            } else if (x > 40) {
               color = 0x00FF00;
            } else if (x > 20) {
               color = 0x008000;
            } else {
               color = 0xff0000;
            }
            return lv_color_hex(color);

display:
  - id: myDisplay
    platform: ili9xxx
    spi_id: spi_bus0
    model: ST7789V
    cs_pin: GPIO40
    dc_pin: GPIO39
    reset_pin: GPIO9
    invert_colors: true
    rotation: 90
    update_interval: never
    auto_clear_enabled: false

lvgl:
  displays:
    - myDisplay
  buffer_size: 25%
  color_depth: 16
  bg_color: 0x000000
  default_font: font_display

  top_layer:
    widgets:
      - label:
          text: "\U000F05A9"
          id: lbl_hastatus
          hidden: true
          align: top_right
          x: 2
          y: 7
          text_align: right
          text_color: 0xFFFFFF
          text_font: font_mdi_tech

  pages:

    - id: waitingBP
      bg_color: 0x000000
      widgets:
        - obj:
            id: idle_center_block_waitingBP
            align: TOP_MID
            width: 320
            height: 110
            y: 3
            bg_opa: TRANSP
            border_opa: TRANSP
            pad_all: 0
            scrollable: false
            widgets:
              - label:
                  id: disp_micro_waitingBP
                  align: TOP_LEFT
                  text: "\U000F036c"
                  text_color: 0xFFFF00
                  text_font: font_mdi_tech
                  x: 5
                  y: 25
                  width: 40
                  long_mode: WRAP
                  text_align: LEFT

              - label:
                  id: lbl_battery_status
                  align: TOP_RIGHT
                  y: 25
                  x: 5
                  text_font: font_mdi_tech
                  text: "\U000F0091" # start with mdi-battery-unknown
                  text_color: 0xFFFF00

              - label:
                  id: disp_powerplug_waitingBP
                  align: TOP_RIGHT
                  y: 25
                  x: -12
                  text_font: font_mdi_tech
                  text: "\U000F1425" # start with outline
                  text_color: 0xFFFF00

              - label:
                  id: disp_microplug_waitingBP
                  align: TOP_LEFT
                  y: 25
                  x: 22
                  text_font: font_mdi_tech
                  text: "\U000F0370" # start with outline
                  text_color: 0x202020

              - label:
                  id: clock_label_waitingBP
                  align: TOP_MID
                  y: 6
                  width: 320
                  text: "--:--:--"
                  text_color: 0xFFFF00
                  text_font: font_7seg
                  text_letter_space: 0
                  text_align: CENTER

        - obj:
            id: idle_meteo_waitingBP
            align: TOP_MID
            x: 5
            y: 60
            width: 310
            height: 70
            bg_opa: TRANSP
            border_opa: TRANSP
            #border_color: 0x00FF00
            pad_all: 0
            scrollable: false
            widgets:
              - label:
                  id: weather_icon_glow
                  align: LEFT_MID
                  x: 19
                  y: 2
                  text: "\U000F0590"
                  text_color: 0x404040
                  text_font: font_mdi_weather

              - label:
                  id: weather_icon
                  align: LEFT_MID
                  x: 18
                  y: 1
                  text: "\U000F0590"
                  text_color: 0xFFFFFF
                  text_font: font_mdi_weather

              - label:
                  id: weather_big_temp
                  align: CENTER
                  x: 0
                  y: 1
                  text: "--"
                  text_color: 0xFFFF00
                  text_font: font_temp_big

              - label:
                  id: weather_big_temp_unit
                  align: CENTER
                  x: 45
                  y: 0
                  text: "°C"
                  text_color: 0xFFFF00
                  text_font: font_temp_unit

        - obj:
            id: idle_center_center_block_waitingBP
            align: TOP_MID
            y: 120
            width: 320
            height: 75
            bg_opa: TRANSP
            border_opa: TRANSP
            pad_all: 0
            scrollable: false
            widgets:
              - label:
                  id: disp_status_waitingBP
                  align: TOP_MID
                  text: "waitingBP"
                  text_color: 0xFFFFFF
                  text_font: font_status
                  y: 0
                  width: 320
                  long_mode: WRAP
                  text_align: CENTER
              - label:
                  id: chanel_waitingBP
                  align: BOTTOM_MID
                  text: "waitingBP"
                  text_color: 0xFFFFFF
                  text_font: font_status
                  y: 0
                  width: 320
                  long_mode: WRAP
                  text_align: CENTER
        - obj:
            id: idle_bottom_center_block_waitingBP
            align: BOTTOM_MID
            y: 0
            width: 320
            height: 50
            bg_opa: TRANSP
            border_opa: TRANSP
            pad_all: 0
            scrollable: false
            widgets:
              - label:
                  id: menu_waitingBP
                  align: TOP_MID
                  text: "waitingBP"
                  text_color: 0xFFFFFF
                  text_font: font_response
                  x: 5
                  y: 5
                  width: 320
                  long_mode: SCROLL_CIRCULAR
                  text_align: CENTER
              - bar:
                  align: BOTTOM_MID
                  width: 300
                  x: 5
                  y: -5
                  id: bar_vol_id
                  transform_height: 3
                  value: 75
                  min_value: 1
                  max_value: 100

    - id: answeringP
      bg_color: 0x000000
      widgets:
        - obj:
            id: idle_center_block_answeringP
            align: CENTER
            width: 240
            height: 230
            bg_opa: TRANSP
            border_opa: TRANSP
            pad_all: 0
            scrollable: false
            widgets:
              - label:
                  id: clock_label_answeringP
                  align: TOP_MID
                  y: 6
                  width: 320
                  text: "--:--:--"
                  text_color: 0xFFFF00
                  text_font: font_7seg
                  text_letter_space: 0
                  text_align: CENTER
        - label:
            align: CENTER
            text: "answeringP"
            text_color: 0xFFFFFF
            text_font: font_boot
            y: 100
            width: 230
            long_mode: WRAP
            text_align: CENTER


