# ir.yaml

binary_sensor:

  - platform: remote_receiver
    name: "IR OK"
    id: ir_ok
    nec:
      address: 0xFE01
      command: 0xF906
    filters:
      - delayed_off: 100ms
    on_click:
      - logger.log: "IR OK received"
  - platform: remote_receiver
    name: "IR UP"
    id: ir_up
    nec:
      address: 0xFE01
      command: 0xFA05
    filters:
      - delayed_off: 100ms
    on_press:
      - logger.log: "IR UP received"
      - number.decrement:
          id: num_shift
          cycle: true
  - platform: remote_receiver
    name: "IR DOWN"
    id: ir_down
    nec:
      address: 0xFE01
      command: 0xFB04
    filters:
      - delayed_off: 100ms
    on_press:
      - logger.log: "IR DOWN received"
      - number.increment:
          id: num_shift
          cycle: true
  - platform: remote_receiver
    name: "IR RIGHT"
    id: ir_right
    nec:
      address: 0xFE01
      command: 0xF50A
    filters:
      - delayed_off: 100ms
    on_press:
      - logger.log: "IR RIGHT received"
      - number.increment:
          id: num_btn
          cycle: true
  - platform: remote_receiver
    name: "IR LEFT"
    id: ir_left
    nec:
      address: 0xFE01
      command: 0xFD02
    filters:
      - delayed_off: 100ms
    on_press:
      - logger.log: "IR LEFT received"
      - number.decrement:
          id: num_btn
          cycle: true
  - platform: remote_receiver
    name: "IR LIKE"
    id: ir_like
    nec:
      address: 0xFE01
      command: 0xF40B
    filters:
      - delayed_off: 100ms
    on_press:
      - logger.log: "IR LIKE received"
      - number.set:
          id: num_shift
          value: 0
      - number.set:
          id: num_btn
          value: 1
  - platform: remote_receiver
    name: "IR HOME"
    id: ir_home
    nec:
      address: 0xFE01
      command: 0xFC03
    filters:
      - delayed_off: 100ms
    on_press:
      - logger.log: "IR HOME received"
      - number.set:
          id: num_shift
          value: 0
      - number.set:
          id: num_btn
          value: 2
  - platform: remote_receiver
    name: "IR BIN"
    id: ir_bin
    nec:
      address: 0xFE01
      command: 0xBB44
    filters:
      - delayed_off: 100ms
    on_press:
      - logger.log: "IR BIN received"
